package it.noesis.erifornimento.model;

import java.util.ArrayList;
import java.util.List;

public class GeoFactory {

    private List<String> provinces;
    private List<String> provincesIds;

    private List<String> nations;
    private List<String> nationsIds;

    public List<String> getNations() {
        return nations;
    }

    public List<String> getNationsIds() {
        return nationsIds;
    }

    public List<String> getProvinces() {
        return provinces;
    }

    public List<String> getProvincesIds() {
        return provincesIds;
    }

    public GeoFactory(){

        provinces = new ArrayList<>();
        provincesIds = new ArrayList<>();

        nations = new ArrayList<>();
        nationsIds = new ArrayList<>();

        nations.add("Afghanistan");
        nations.add("Albania");
        nations.add("Algeria");
        nations.add("Andorra");
        nations.add("Angola");
        nations.add("Anguilla");
        nations.add("Antartide");
        nations.add("Antigua e Barbuda");
        nations.add("Antille Francesi");
        nations.add("Arabia Saudita");
        nations.add("Argentina");
        nations.add("Armenia");
        nations.add("Aruba");
        nations.add("Australia");
        nations.add("Austria");
        nations.add("Azerbaijan");
        nations.add("Bahamas");
        nations.add("Bahrein");
        nations.add("Bangladesh");
        nations.add("Barbados");
        nations.add("Belgio");
        nations.add("Belize");
        nations.add("Benin");
        nations.add("Bermuda");
        nations.add("Bhutan");
        nations.add("Bielorussia");
        nations.add("Birmania");
        nations.add("Bolivia");
        nations.add("Bonaire, Saint-Eustache e Saba");
        nations.add("Bosnia ed Erzegovina");
        nations.add("Botswana");
        nations.add("Brasile");
        nations.add("Brunei");
        nations.add("Bulgaria");
        nations.add("Burkina Faso");
        nations.add("Burundi");
        nations.add("Cambogia");
        nations.add("Camerun");
        nations.add("Canada");
        nations.add("Capo Verde");
        nations.add("Ciad");
        nations.add("Cile");
        nations.add("Cina");
        nations.add("Cipro");
        nations.add("Colombia");
        nations.add("Comore");
        nations.add("Congo");
        nations.add("Congo (Rep. Dem.)");
        nations.add("Corea del Nord");
        nations.add("Corea del Sud");
        nations.add("Costa D'Avorio");
        nations.add("Costa Rica");
        nations.add("Croazia");
        nations.add("Cuba");
        nations.add("Curacao");
        nations.add("Danimarca");
        nations.add("Dominica");
        nations.add("Ecuador");
        nations.add("Egitto");
        nations.add("El Salvador");
        nations.add("Emirati Arabi Uniti");
        nations.add("Eritrea");
        nations.add("Estonia");
        nations.add("Etiopia");
        nations.add("Figi");
        nations.add("Filippine");
        nations.add("Finlandia");
        nations.add("Francia");
        nations.add("Gabon");
        nations.add("Gambia");
        nations.add("Georgia");
        nations.add("Georgia del Sud e Isole Sandwich Meridionali");
        nations.add("Germania");
        nations.add("Ghana");
        nations.add("Giamaica");
        nations.add("Giappone");
        nations.add("Gibilterra");
        nations.add("Gibuti");
        nations.add("Giordania");
        nations.add("Grecia");
        nations.add("Grenada");
        nations.add("Groenlandia");
        nations.add("Guadeloupa");
        nations.add("Guam");
        nations.add("Guatemala");
        nations.add("Guernsey");
        nations.add("Guinea");
        nations.add("Guinea Equatoriale");
        nations.add("Guinea-Bissau");
        nations.add("Guyana");
        nations.add("Guyana francese");
        nations.add("Haiti");
        nations.add("Honduras");
        nations.add("Hong Kong");
        nations.add("India");
        nations.add("Indonesia");
        nations.add("Iran");
        nations.add("Iraq");
        nations.add("Irlanda");
        nations.add("Islanda");
        nations.add("Isola Bouvet");
        nations.add("Isola Norfolk");
        nations.add("Isola di Jersey");
        nations.add("Isola di Man");
        nations.add("Isola di Natale");
        nations.add("Isole Aland");
        nations.add("Isole Cayman");
        nations.add("Isole Cocos e Keeling");
        nations.add("Isole Cook");
        nations.add("Isole Falkland o Isole Malvine");
        nations.add("Isole Far Oer");
        nations.add("Isole Heard e McDonald");
        nations.add("Isole Marianne Settentrionali");
        nations.add("Isole Marshall");
        nations.add("Isole Pitcairn");
        nations.add("Isole Salomone");
        nations.add("Isole Tokelau");
        nations.add("Isole Turks e Caicos");
        nations.add("Isole Vergini Britanniche");
        nations.add("Isole Vergini americane");
        nations.add("Isole minori esterne degli Stati Uniti d'America");
        nations.add("Israele");
        nations.add("Italia");
        nations.add("Kazakistan");
        nations.add("Kenya");
        nations.add("Kirghizistan");
        nations.add("Kiribati");
        nations.add("Kossovo");
        nations.add("Kuwait");
        nations.add("Laos");
        nations.add("Lesotho");
        nations.add("Lettonia");
        nations.add("Libano");
        nations.add("Liberia");
        nations.add("Libia");
        nations.add("Liechtenstein");
        nations.add("Lituania");
        nations.add("Lussemburgo");
        nations.add("Macao");
        nations.add("Macedonia");
        nations.add("Madagascar");
        nations.add("Malawi");
        nations.add("Maldive");
        nations.add("Malesia");
        nations.add("Mali");
        nations.add("Malta");
        nations.add("Marocco");
        nations.add("Martinica");
        nations.add("Mauritania");
        nations.add("Mauritius");
        nations.add("Mayotte");
        nations.add("Messico");
        nations.add("Micronesia");
        nations.add("Moldavia");
        nations.add("Mongolia");
        nations.add("Montenegro");
        nations.add("Montserrat");
        nations.add("Mozambico");
        nations.add("Namibia");
        nations.add("Nauru");
        nations.add("Nepal");
        nations.add("Nicaragua");
        nations.add("Niger");
        nations.add("Nigeria");
        nations.add("Niue");
        nations.add("Norvegia");
        nations.add("Nuova Caledonia");
        nations.add("Nuova Zelanda");
        nations.add("Oman");
        nations.add("Paesi Bassi");
        nations.add("Pakistan");
        nations.add("Palau");
        nations.add("Palestina");
        nations.add("Panama");
        nations.add("Papua Nuova Guinea");
        nations.add("Paraguay");
        nations.add("Perù");
        nations.add("Polinesia Francese");
        nations.add("Polonia");
        nations.add("Porto Rico");
        nations.add("Portogallo");
        nations.add("Principato di Monaco");
        nations.add("Qatar");
        nations.add("Regno Unito");
        nations.add("Repubblica Ceca");
        nations.add("Repubblica Centrafricana");
        nations.add("Repubblica Dominicana");
        nations.add("Riunione");
        nations.add("Romania");
        nations.add("Ruanda");
        nations.add("Russia");
        nations.add("Sahara Occidentale");
        nations.add("Saint Kitts e Nevis");
        nations.add("Saint Martin");
        nations.add("Saint Martin (parte olandese)");
        nations.add("Saint Vincent e Grenadine");
        nations.add("Saint-Pierre e Miquelon");
        nations.add("Samoa");
        nations.add("Samoa Americane");
        nations.add("San Marino");
        nations.add("Sant'Elena");
        nations.add("Santa Lucia");
        nations.add("Santa Sede");
        nations.add("Sao Tome and Principe");
        nations.add("Senegal");
        nations.add("Serbia");
        nations.add("Seychelles");
        nations.add("Sierra Leone");
        nations.add("Singapore");
        nations.add("Siria");
        nations.add("Slovacchia");
        nations.add("Slovenia");
        nations.add("Somalia");
        nations.add("Spagna");
        nations.add("Sri Lanka");
        nations.add("Stati Uniti D'America");
        nations.add("Sud Africa");
        nations.add("Sudan");
        nations.add("Sudan del sud");
        nations.add("Suriname");
        nations.add("Svalbard e Jan Mayen");
        nations.add("Svezia");
        nations.add("Svizzera");
        nations.add("Swaziland");
        nations.add("Tagikistan");
        nations.add("Tailandia");
        nations.add("Taiwan");
        nations.add("Tanzania");
        nations.add("Territori Francesi del Sud");
        nations.add("Territorio britannico dell'oceano indiano");
        nations.add("Timor Est");
        nations.add("Togo");
        nations.add("Tonga");
        nations.add("Trinidad e Tobago");
        nations.add("Tunisia");
        nations.add("Turchia");
        nations.add("Turkmenistan");
        nations.add("Tuvalu");
        nations.add("Ucraina");
        nations.add("Uganda");
        nations.add("Ungheria");
        nations.add("Uruguay");
        nations.add("Uzbekistan");
        nations.add("Vanuatu");
        nations.add("Venezuela");
        nations.add("Vietnam");
        nations.add("Wallis e Futuna");
        nations.add("Yemen");
        nations.add("Zambia");
        nations.add("Zimbabwe");


        nationsIds.add("AF");
        nationsIds.add("AL");
        nationsIds.add("DZ");
        nationsIds.add("AD");
        nationsIds.add("AO");
        nationsIds.add("AI");
        nationsIds.add("AQ");
        nationsIds.add("AG");
        nationsIds.add("BL");
        nationsIds.add("SA");
        nationsIds.add("AR");
        nationsIds.add("AM");
        nationsIds.add("AW");
        nationsIds.add("AU");
        nationsIds.add("AT");
        nationsIds.add("AZ");
        nationsIds.add("BS");
        nationsIds.add("BH");
        nationsIds.add("BD");
        nationsIds.add("BB");
        nationsIds.add("BE");
        nationsIds.add("BZ");
        nationsIds.add("BJ");
        nationsIds.add("BM");
        nationsIds.add("BT");
        nationsIds.add("BY");
        nationsIds.add("MM");
        nationsIds.add("BO");
        nationsIds.add("BQ");
        nationsIds.add("BA");
        nationsIds.add("BW");
        nationsIds.add("BR");
        nationsIds.add("BN");
        nationsIds.add("BG");
        nationsIds.add("BF");
        nationsIds.add("BI");
        nationsIds.add("KH");
        nationsIds.add("CM");
        nationsIds.add("CA");
        nationsIds.add("CV");
        nationsIds.add("TD");
        nationsIds.add("CL");
        nationsIds.add("CN");
        nationsIds.add("CY");
        nationsIds.add("CO");
        nationsIds.add("KM");
        nationsIds.add("CG");
        nationsIds.add("CD");
        nationsIds.add("KP");
        nationsIds.add("KR");
        nationsIds.add("CI");
        nationsIds.add("CR");
        nationsIds.add("HR");
        nationsIds.add("CU");
        nationsIds.add("CW");
        nationsIds.add("DK");
        nationsIds.add("DM");
        nationsIds.add("EC");
        nationsIds.add("EG");
        nationsIds.add("SV");
        nationsIds.add("AE");
        nationsIds.add("ER");
        nationsIds.add("EE");
        nationsIds.add("ET");
        nationsIds.add("FJ");
        nationsIds.add("PH");
        nationsIds.add("FI");
        nationsIds.add("FR");
        nationsIds.add("GA");
        nationsIds.add("GM");
        nationsIds.add("GE");
        nationsIds.add("GS");
        nationsIds.add("DE");
        nationsIds.add("GH");
        nationsIds.add("JM");
        nationsIds.add("JP");
        nationsIds.add("GI");
        nationsIds.add("DJ");
        nationsIds.add("JO");
        nationsIds.add("GR");
        nationsIds.add("GD");
        nationsIds.add("GL");
        nationsIds.add("GP");
        nationsIds.add("GU");
        nationsIds.add("GT");
        nationsIds.add("GG");
        nationsIds.add("GN");
        nationsIds.add("GQ");
        nationsIds.add("GW");
        nationsIds.add("GY");
        nationsIds.add("GF");
        nationsIds.add("HT");
        nationsIds.add("HN");
        nationsIds.add("HK");
        nationsIds.add("IN");
        nationsIds.add("ID");
        nationsIds.add("IR");
        nationsIds.add("IQ");
        nationsIds.add("IE");
        nationsIds.add("IS");
        nationsIds.add("BV");
        nationsIds.add("NF");
        nationsIds.add("JE");
        nationsIds.add("IM");
        nationsIds.add("CX");
        nationsIds.add("AX");
        nationsIds.add("KY");
        nationsIds.add("CC");
        nationsIds.add("CK");
        nationsIds.add("FK");
        nationsIds.add("FO");
        nationsIds.add("HM");
        nationsIds.add("MP");
        nationsIds.add("MH");
        nationsIds.add("PN");
        nationsIds.add("SB");
        nationsIds.add("TK");
        nationsIds.add("TC");
        nationsIds.add("VG");
        nationsIds.add("VI");
        nationsIds.add("UM");
        nationsIds.add("IL");
        nationsIds.add("IT");
        nationsIds.add("KZ");
        nationsIds.add("KE");
        nationsIds.add("KG");
        nationsIds.add("KI");
        nationsIds.add("XK");
        nationsIds.add("KW");
        nationsIds.add("LA");
        nationsIds.add("LS");
        nationsIds.add("LV");
        nationsIds.add("LB");
        nationsIds.add("LR");
        nationsIds.add("LY");
        nationsIds.add("LI");
        nationsIds.add("LT");
        nationsIds.add("LU");
        nationsIds.add("MO");
        nationsIds.add("MK");
        nationsIds.add("MG");
        nationsIds.add("MW");
        nationsIds.add("MV");
        nationsIds.add("MY");
        nationsIds.add("ML");
        nationsIds.add("MT");
        nationsIds.add("MA");
        nationsIds.add("MQ");
        nationsIds.add("MR");
        nationsIds.add("MU");
        nationsIds.add("YT");
        nationsIds.add("MX");
        nationsIds.add("FM");
        nationsIds.add("MD");
        nationsIds.add("MN");
        nationsIds.add("ME");
        nationsIds.add("MS");
        nationsIds.add("MZ");
        nationsIds.add("NA");
        nationsIds.add("NR");
        nationsIds.add("NP");
        nationsIds.add("NI");
        nationsIds.add("NE");
        nationsIds.add("NG");
        nationsIds.add("NU");
        nationsIds.add("NO");
        nationsIds.add("NC");
        nationsIds.add("NZ");
        nationsIds.add("OM");
        nationsIds.add("NL");
        nationsIds.add("PK");
        nationsIds.add("PW");
        nationsIds.add("PS");
        nationsIds.add("PA");
        nationsIds.add("PG");
        nationsIds.add("PY");
        nationsIds.add("PE");
        nationsIds.add("PF");
        nationsIds.add("PL");
        nationsIds.add("PR");
        nationsIds.add("PT");
        nationsIds.add("MC");
        nationsIds.add("QA");
        nationsIds.add("GB");
        nationsIds.add("CZ");
        nationsIds.add("CF");
        nationsIds.add("DO");
        nationsIds.add("RE");
        nationsIds.add("RO");
        nationsIds.add("RW");
        nationsIds.add("RU");
        nationsIds.add("EH");
        nationsIds.add("KN");
        nationsIds.add("MF");
        nationsIds.add("SX");
        nationsIds.add("VC");
        nationsIds.add("PM");
        nationsIds.add("WS");
        nationsIds.add("AS");
        nationsIds.add("SM");
        nationsIds.add("SH");
        nationsIds.add("LC");
        nationsIds.add("VA");
        nationsIds.add("ST");
        nationsIds.add("SN");
        nationsIds.add("RS");
        nationsIds.add("SC");
        nationsIds.add("SL");
        nationsIds.add("SG");
        nationsIds.add("SY");
        nationsIds.add("SK");
        nationsIds.add("SI");
        nationsIds.add("SO");
        nationsIds.add("ES");
        nationsIds.add("LK");
        nationsIds.add("US");
        nationsIds.add("ZA");
        nationsIds.add("SD");
        nationsIds.add("SS");
        nationsIds.add("SR");
        nationsIds.add("SJ");
        nationsIds.add("SE");
        nationsIds.add("CH");
        nationsIds.add("SZ");
        nationsIds.add("TJ");
        nationsIds.add("TH");
        nationsIds.add("TW");
        nationsIds.add("TZ");
        nationsIds.add("TF");
        nationsIds.add("IO");
        nationsIds.add("TL");
        nationsIds.add("TG");
        nationsIds.add("TO");
        nationsIds.add("TT");
        nationsIds.add("TN");
        nationsIds.add("TR");
        nationsIds.add("TM");
        nationsIds.add("TV");
        nationsIds.add("UA");
        nationsIds.add("UG");
        nationsIds.add("HU");
        nationsIds.add("UY");
        nationsIds.add("UZ");
        nationsIds.add("VU");
        nationsIds.add("VE");
        nationsIds.add("VN");
        nationsIds.add("WF");
        nationsIds.add("YE");
        nationsIds.add("ZM");
        nationsIds.add("ZW");

        provinces.add("");
        provinces.add("Agrigento");
        provinces.add("Alessandria");
        provinces.add("Ancona");
        provinces.add("Aosta");
        provinces.add("Arezzo");
        provinces.add("Ascoli Piceno");
        provinces.add("Asti");
        provinces.add("Avellino");
        provinces.add("Bari");
        provinces.add("Barletta-Andria-Trani");
        provinces.add("Belluno");
        provinces.add("Benevento");
        provinces.add("Bergamo");
        provinces.add("Biella");
        provinces.add("Bologna");
        provinces.add("Bolzano");
        provinces.add("Brescia");
        provinces.add("Brindisi");
        provinces.add("Cagliari");
        provinces.add("Caltanissetta");
        provinces.add("Campobasso");
        provinces.add("Carbonia-Iglesias");
        provinces.add("Caserta");
        provinces.add("Catania");
        provinces.add("Catanzaro");
        provinces.add("Chieti");
        provinces.add("Como");
        provinces.add("Cosenza");
        provinces.add("Cremona");
        provinces.add("Crotone");
        provinces.add("Cuneo");
        provinces.add("Enna");
        provinces.add("Fermo");
        provinces.add("Ferrara");
        provinces.add("Firenze");
        provinces.add("Fiume");
        provinces.add("Foggia");
        provinces.add("Forlì-Cesena");
        provinces.add("Frosinone");
        provinces.add("Genova");
        provinces.add("Gorizia");
        provinces.add("Grosseto");
        provinces.add("Imperia");
        provinces.add("Isernia");
        provinces.add("La Spezia");
        provinces.add("L'aquila");
        provinces.add("Latina");
        provinces.add("Lecce");
        provinces.add("Lecco");
        provinces.add("Livorno");
        provinces.add("Lodi");
        provinces.add("Lucca");
        provinces.add("Macerata");
        provinces.add("Mantova");
        provinces.add("Massa Carrara");
        provinces.add("Matera");
        provinces.add("Medio-Campidano");
        provinces.add("Messina");
        provinces.add("Milano");
        provinces.add("Modena");
        provinces.add("Monza e Brianza");
        provinces.add("Napoli");
        provinces.add("Novara");
        provinces.add("Nuoro");
        provinces.add("Ogliastra");
        provinces.add("Olbia-Tempio");
        provinces.add("Oristano");
        provinces.add("Padova");
        provinces.add("Palermo");
        provinces.add("Parma");
        provinces.add("Pavia");
        provinces.add("Perugia");
        provinces.add("Pesaro-Urbino");
        provinces.add("Pescara");
        provinces.add("Piacenza");
        provinces.add("Pisa");
        provinces.add("Pistoia");
        provinces.add("Pola");
        provinces.add("Pordenone");
        provinces.add("Potenza");
        provinces.add("Prato");
        provinces.add("Ragusa");
        provinces.add("Ravenna");
        provinces.add("Reggio C.");
        provinces.add("Reggio E.");
        provinces.add("Rieti");
        provinces.add("Rimini");
        provinces.add("Roma");
        provinces.add("Rovigo");
        provinces.add("Salerno");
        provinces.add("Sassari");
        provinces.add("Savona");
        provinces.add("Siena");
        provinces.add("Siracusa");
        provinces.add("Sondrio");
        provinces.add("Stato Estero");
        provinces.add("Taranto");
        provinces.add("Teramo");
        provinces.add("Terni");
        provinces.add("Torino");
        provinces.add("Trapani");
        provinces.add("Trento");
        provinces.add("Treviso");
        provinces.add("Trieste");
        provinces.add("Udine");
        provinces.add("Varese");
        provinces.add("Venezia");
        provinces.add("Verbania");
        provinces.add("Vercelli");
        provinces.add("Verona");
        provinces.add("Vibo Valentia");
        provinces.add("Vicenza");
        provinces.add("Viterbo");
        provinces.add("Zara");

        provincesIds.add("");
        provincesIds.add("AG");
        provincesIds.add("AL");
        provincesIds.add("AN");
        provincesIds.add("AO");
        provincesIds.add("AR");
        provincesIds.add("AP");
        provincesIds.add("AT");
        provincesIds.add("AV");
        provincesIds.add("BA");
        provincesIds.add("BT");
        provincesIds.add("BL");
        provincesIds.add("BN");
        provincesIds.add("BG");
        provincesIds.add("BI");
        provincesIds.add("BO");
        provincesIds.add("BZ");
        provincesIds.add("BS");
        provincesIds.add("BR");
        provincesIds.add("CA");
        provincesIds.add("CL");
        provincesIds.add("CB");
        provincesIds.add("CI");
        provincesIds.add("CE");
        provincesIds.add("CT");
        provincesIds.add("CZ");
        provincesIds.add("CH");
        provincesIds.add("CO");
        provincesIds.add("CS");
        provincesIds.add("CR");
        provincesIds.add("KR");
        provincesIds.add("CN");
        provincesIds.add("EN");
        provincesIds.add("FM");
        provincesIds.add("FE");
        provincesIds.add("FI");
        provincesIds.add("FU");
        provincesIds.add("FG");
        provincesIds.add("FC");
        provincesIds.add("FR");
        provincesIds.add("GE");
        provincesIds.add("GO");
        provincesIds.add("GR");
        provincesIds.add("IM");
        provincesIds.add("IS");
        provincesIds.add("SP");
        provincesIds.add("AQ");
        provincesIds.add("LT");
        provincesIds.add("LE");
        provincesIds.add("LC");
        provincesIds.add("LI");
        provincesIds.add("LO");
        provincesIds.add("LU");
        provincesIds.add("MC");
        provincesIds.add("MN");
        provincesIds.add("MS");
        provincesIds.add("MT");
        provincesIds.add("VS");
        provincesIds.add("ME");
        provincesIds.add("MI");
        provincesIds.add("MO");
        provincesIds.add("MB");
        provincesIds.add("NA");
        provincesIds.add("NO");
        provincesIds.add("NU");
        provincesIds.add("OG");
        provincesIds.add("OT");
        provincesIds.add("OR");
        provincesIds.add("PD");
        provincesIds.add("PA");
        provincesIds.add("PR");
        provincesIds.add("PV");
        provincesIds.add("PG");
        provincesIds.add("PU");
        provincesIds.add("PE");
        provincesIds.add("PC");
        provincesIds.add("PI");
        provincesIds.add("PT");
        provincesIds.add("PL");
        provincesIds.add("PN");
        provincesIds.add("PZ");
        provincesIds.add("PO");
        provincesIds.add("RG");
        provincesIds.add("RA");
        provincesIds.add("RC");
        provincesIds.add("RE");
        provincesIds.add("RI");
        provincesIds.add("RN");
        provincesIds.add("RM");
        provincesIds.add("RO");
        provincesIds.add("SA");
        provincesIds.add("SS");
        provincesIds.add("SV");
        provincesIds.add("SI");
        provincesIds.add("SR");
        provincesIds.add("SO");
        provincesIds.add("XX");
        provincesIds.add("TA");
        provincesIds.add("TE");
        provincesIds.add("TR");
        provincesIds.add("TO");
        provincesIds.add("TP");
        provincesIds.add("TN");
        provincesIds.add("TV");
        provincesIds.add("TS");
        provincesIds.add("UD");
        provincesIds.add("VA");
        provincesIds.add("VE");
        provincesIds.add("VB");
        provincesIds.add("VC");
        provincesIds.add("VR");
        provincesIds.add("VV");
        provincesIds.add("VI");
        provincesIds.add("VT");
        provincesIds.add("ZA");



    }


}
